// src/Presentation/Client/Presentation.Client.Web.Vue.js/presentation.client.web.vue.js/src/App.vue
<template>
  <div class="chat-container">
    <!-- فضای نمایش پیام‌ها -->   
    <div class="chat-area">  
      <div class="message-list">
        <div v-for="(message, index) in messages" :key="index"
          :class="['message', message.from.guid === me.guid ? 'mine' : 'theirs']">
          <span class="from">{{ message.from.name }}</span>
          <div class="content">{{ message.message }}</div>
          <span class="time">{{ message.sendTime }}</span>
        </div>
      </div>

      <!-- فرم ورود -->
      <div v-if="!loggedIn" class="message-input">
        <input type="text" v-model="name" placeholder="نام خود را بنویسید..." />
        <button :disabled="name.length < 3" @click="login">شروع</button>
      </div>

      <!-- فرم ارسال پیام -->
      <div v-else class="message-input">
        <input type="text" v-model="newMessage" placeholder="پیام خود را بنویسید..." />
        <button :disabled="!newMessage.trim()" @click="sendMessage">ارسال</button>
      </div>
    </div>
  </div>
</template>

<script>

import * as signalR from "@microsoft/signalr";
import { v4 as uuidv4 } from 'uuid';
import { format } from 'date-fns';

export default {
  data() {
    return {
      connection: null, // اتصال SignalR
      name: "", // نام کاربر
      newMessage: "", // پیام جدید
      messages: [], // لیست پیام‌ها
      loggedIn: false, // وضعیت ورود
      me: null, // اطلاعات کاربر
    };
  },
  methods: {
    async login() {
      try {
        this.me =
        {
          guid: uuidv4(),
          name: this.name,
          device: "hi"
        }; // مشخصات کاربر

        console.log(this.me);

        var url = window.location.origin;

        url = url.replace(/:\d+/, ':8080');

        this.connection = new signalR.HubConnectionBuilder()
          .withUrl(url + "/chathub") // آدرس SignalR
          .configureLogging(signalR.LogLevel.Information)
          .build();

        // تنظیمات دریافت پیام
        this.connection.on("ReceiveMessage", (message) => {
          this.messages.push(message);
        });

        await this.connection.start();
        this.loggedIn = true;
      } catch (err) {
        console.error("خطا در اتصال:", err);
      }
    },
    async sendMessage() {
      if (this.connection) {
        try {
          const message = {
            from: this.me,
            message: this.newMessage,
            sendTime: format(new Date(), 'HH:mm:ss'),
          };

          console.log(message);

          await this.connection.invoke("SendMessage", message);
          this.messages.push(message);
          this.newMessage = "";

        } catch (err) {
          console.error("خطا در ارسال پیام:", err);
        }
      }
    },
  },
};
</script>

// src/Presentation/Client/Peresentation.Client.Web.Angular.App/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HubConnection, HubConnectionBuilder, LogLevel } from '@microsoft/signalr';
import { v4 as uuidv4 } from 'uuid';
import { format } from 'date-fns';
import { RouterOutlet } from '@angular/router';
import {FormsModule  } from '@angular/forms';

@Component({
  standalone: true,
  selector: 'app-root',
  imports: [RouterOutlet,CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})

export class AppComponent {
  connection!: HubConnection | null; // اتصال SignalR
  name: string = ''; // نام کاربر
  newMessage: string = ''; // پیام جدید
  messages: Message[] = []; // لیست پیام‌ها
  loggedIn: boolean = false; // وضعیت ورود
  me?: SenderUser; // اطلاعات کاربر

  async login() {
    try {
      this.me = {
        guid: uuidv4(),
        name: this.name,
        device: 'hi'
      }; // مشخصات کاربر

      console.log(this.me);

      var url = window.location.origin;
      url = url.replace(/:\d+/, ':8080');

      this.connection = new HubConnectionBuilder()
        .withUrl(url + '/chathub') // آدرس SignalR
        .configureLogging(LogLevel.Information)
        .build();

      // تنظیمات دریافت پیام
      this.connection.on('ReceiveMessage', (message) => {
        this.messages.push(message);
      });

      await this.connection.start();
      this.loggedIn = true;
    } catch (err) {
      console.error('خطا در اتصال:', err);
    }
  }

  async sendMessage() {
    if (this.connection) {
      try {
        const message : Message= {
          from: this.me!,
          message: this.newMessage,
          sendTime: format(new Date(), 'HH:mm:ss')
        };

        console.log(message);

        await this.connection.invoke('SendMessage', message);
        this.messages.push(message);
        this.newMessage = '';
      } catch (err) {
        console.error('خطا در ارسال پیام:', err);
      }
    }
  }
}

export interface SenderUser {
  guid: string;
  name: string;
  device: string;
}

export interface Message {
  from: SenderUser;
  message: string;
  sendTime: string;
}
<div class="chat-container">
  <!-- فضای نمایش پیام‌ها -->
  <div class="chat-area">
    <div class="message-list">
      <div *ngFor="let message of messages; let index = index" [ngClass]="{'message': true, 'mine': message!.from!.guid === me!.guid, 'theirs': message!.from!.guid !== me!.guid}">
        <span class="from">{{ message!.from!.name }}</span>
        <div class="content">{{ message!.message }}</div>
        <span class="time">{{ message!.sendTime }}</span>
      </div>
    </div>

    <!-- فرم ورود -->
    <div *ngIf="!loggedIn" class="message-input">
      <input type="text" [(ngModel)]="name" placeholder="نام خود را بنویسید..." />
      <button [disabled]="name.length < 3" (click)="login()">شروع</button>
    </div>

    <!-- فرم ارسال پیام -->
    <div *ngIf="loggedIn" class="message-input">
      <input type="text" [(ngModel)]="newMessage" placeholder="پیام خود را بنویسید..." />
      <button [disabled]="!newMessage.trim()" (click)="sendMessage()">ارسال</button>
    </div>
  </div>
</div>
